// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_attendance from "./routes/api/attendance.ts";
import * as $api_auth_google from "./routes/api/auth/google.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_edit_information from "./routes/api/edit-information.ts";
import * as $api_practice_times from "./routes/api/practice-times.ts";
import * as $api_resend_email from "./routes/api/resend-email.ts";
import * as $api_verify_email from "./routes/api/verify-email.ts";
import * as $attendance_settings from "./routes/attendance-settings.tsx";
import * as $database_attendance from "./routes/database/attendance.ts";
import * as $database_practice_times from "./routes/database/practice-times.ts";
import * as $database_role from "./routes/database/role.ts";
import * as $database_session from "./routes/database/session.ts";
import * as $database_user from "./routes/database/user.ts";
import * as $google_supplement from "./routes/google-supplement.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $register from "./routes/register.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $AttendanceForm from "./islands/AttendanceForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GoogleAuthButtons from "./islands/GoogleAuthButtons.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $NavAuth from "./islands/NavAuth.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $Notification from "./islands/Notification.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $ResendEmail from "./islands/ResendEmail.tsx";
import * as $SettingsForm from "./islands/SettingsForm.tsx";
import * as $TestIsland from "./islands/TestIsland.tsx";
import * as $TimeChart from "./islands/TimeChart.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/attendance.ts": $api_attendance,
    "./routes/api/auth/google.ts": $api_auth_google,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/edit-information.ts": $api_edit_information,
    "./routes/api/practice-times.ts": $api_practice_times,
    "./routes/api/resend-email.ts": $api_resend_email,
    "./routes/api/verify-email.ts": $api_verify_email,
    "./routes/attendance-settings.tsx": $attendance_settings,
    "./routes/database/attendance.ts": $database_attendance,
    "./routes/database/practice-times.ts": $database_practice_times,
    "./routes/database/role.ts": $database_role,
    "./routes/database/session.ts": $database_session,
    "./routes/database/user.ts": $database_user,
    "./routes/google-supplement.tsx": $google_supplement,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/register.tsx": $register,
    "./routes/settings.tsx": $settings,
  },
  islands: {
    "./islands/AttendanceForm.tsx": $AttendanceForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/GoogleAuthButtons.tsx": $GoogleAuthButtons,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/NavAuth.tsx": $NavAuth,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/Notification.tsx": $Notification,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/ResendEmail.tsx": $ResendEmail,
    "./islands/SettingsForm.tsx": $SettingsForm,
    "./islands/TestIsland.tsx": $TestIsland,
    "./islands/TimeChart.tsx": $TimeChart,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
